
package ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BanqueWS", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueWS {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertToDh", targetNamespace = "http://ws/", className = "ws.ConvertToDh")
    @ResponseWrapper(localName = "convertToDhResponse", targetNamespace = "http://ws/", className = "ws.ConvertToDhResponse")
    @Action(input = "http://ws/BanqueWS/convertToDhRequest", output = "http://ws/BanqueWS/convertToDhResponse")
    public double convertToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns ws.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws/", className = "ws.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws/", className = "ws.GetCompteResponse")
    @Action(input = "http://ws/BanqueWS/getCompteRequest", output = "http://ws/BanqueWS/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        Long code);

    /**
     * 
     * @return
     *     returns java.util.List<ws.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listCompte", targetNamespace = "http://ws/", className = "ws.ListCompte")
    @ResponseWrapper(localName = "listCompteResponse", targetNamespace = "http://ws/", className = "ws.ListCompteResponse")
    @Action(input = "http://ws/BanqueWS/listCompteRequest", output = "http://ws/BanqueWS/listCompteResponse")
    public List<Compte> listCompte();

}
